import express from 'express';
import Patient from '../models/Patient.js';
import { authenticate, authorize } from '../middleware/auth.js';

const router = express.Router();

// Get all patients (admin only)
router.get('/', authenticate, authorize(['admin']), async (req, res) => {
  try {
    const patients = await Patient.find()
      .populate('userId', 'name email')
      .populate('createdBy', 'name')
      .sort({ createdAt: -1 });
    
    res.json({ success: true, patients });
  } catch (error) {
    console.error('Error fetching patients:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// Search patients by name, email, or patientId (admin only)
router.get('/search/query', authenticate, authorize(['admin']), async (req, res) => {
  try {
    const { q } = req.query;
    
    if (!q || q.trim().length === 0) {
      return res.json({ success: true, patients: [] });
    }

    const patients = await Patient.find({
      $or: [
        { fullName: { $regex: q, $options: 'i' } },
        { email: { $regex: q, $options: 'i' } },
        { patientId: { $regex: q, $options: 'i' } },
        { phone: { $regex: q, $options: 'i' } }
      ]
    })
      .populate('userId', 'name email')
      .populate('createdBy', 'name')
      .sort({ createdAt: -1 });
    
    res.json({ success: true, patients });
  } catch (error) {
    console.error('Error searching patients:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// Get patient by ID
router.get('/:id', authenticate, async (req, res) => {
  try {
    const patient = await Patient.findById(req.params.id)
      .populate('userId', 'name email')
      .populate('createdBy', 'name');
    
    if (!patient) {
      return res.status(404).json({ success: false, message: 'Patient not found' });
    }

    // Allow admin or the patient themselves
    if (req.userId !== patient.userId.toString() && req.userRole !== 'admin') {
      return res.status(403).json({ success: false, message: 'Unauthorized' });
    }

    res.json({ success: true, patient });
  } catch (error) {
    console.error('Error fetching patient:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// Create patient (authenticated users)
router.post('/', authenticate, async (req, res) => {
  try {
    const { fullName, email, phone, dateOfBirth, gender, address, medicalHistory, bloodGroup } = req.body;

    // Validation
    if (!fullName || !email || !phone || !dateOfBirth || !gender) {
      return res.status(400).json({ 
        success: false, 
        message: 'Please provide all required fields: fullName, email, phone, dateOfBirth, gender' 
      });
    }

    // Check if patient with same email already exists
    const existingPatient = await Patient.findOne({ email: email.toLowerCase().trim() });
    if (existingPatient) {
      return res.status(400).json({
        success: false,
        message: 'A patient with this email already exists'
      });
    }

    // Create patient without manually setting patientId - let the pre-validate hook handle it
    const patient = new Patient({
      fullName: fullName.trim(),
      email: email.toLowerCase().trim(),
      phone: phone.trim(),
      dateOfBirth: new Date(dateOfBirth),
      gender: gender.trim(),
      address: address?.trim() || null,
      medicalHistory: medicalHistory?.trim() || null,
      bloodGroup: bloodGroup || null,
      userId: req.userId,
      createdBy: req.userId
      // patientId will be auto-generated by the pre-validate hook
    });

    // Save the patient
    await patient.save();
    await patient.populate('userId', 'name email');

    res.status(201).json({
      success: true,
      message: 'Patient registered successfully',
      patient
    });
  } catch (error) {
    console.error('Error creating patient:', error);
    
    // Handle duplicate email error
    if (error.code === 11000 && error.keyPattern && error.keyPattern.email) {
      return res.status(400).json({
        success: false,
        message: 'A patient with this email already exists'
      });
    }

    res.status(500).json({ 
      success: false, 
      message: error.message || 'Error creating patient' 
    });
  }
});

// Update patient
router.put('/:id', authenticate, async (req, res) => {
  try {
    const patient = await Patient.findById(req.params.id);
    
    if (!patient) {
      return res.status(404).json({ success: false, message: 'Patient not found' });
    }

    // Check authorization
    if (req.userId !== patient.userId.toString() && req.userRole !== 'admin') {
      return res.status(403).json({ success: false, message: 'Unauthorized' });
    }

    // Prevent patientId from being updated
    const { patientId, ...updateData } = req.body;

    const updatedPatient = await Patient.findByIdAndUpdate(
      req.params.id,
      updateData,
      { new: true, runValidators: true }
    ).populate('userId', 'name email');

    res.json({ success: true, message: 'Patient updated successfully', patient: updatedPatient });
  } catch (error) {
    console.error('Error updating patient:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// Delete patient
router.delete('/:id', authenticate, authorize(['admin']), async (req, res) => {
  try {
    const patient = await Patient.findById(req.params.id);
    
    if (!patient) {
      return res.status(404).json({ success: false, message: 'Patient not found' });
    }

    await Patient.findByIdAndDelete(req.params.id);

    res.json({ success: true, message: 'Patient deleted successfully' });
  } catch (error) {
    console.error('Error deleting patient:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

export default router;